/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_dramascript_ndktest_NdkTools */

#ifndef _Included_com_dramascript_ndktest_NdkTools
#define _Included_com_dramascript_ndktest_NdkTools
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_dramascript_ndktest_NdkTools
 * Method:    getBoolean
 * Signature: (Z)Z
 */
JNIEXPORT jboolean JNICALL Java_com_dramascript_ndktest_NdkTools_getBoolean
        (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_dramascript_ndktest_NdkTools
 * Method:    getByte
 * Signature: (B)B
 */
JNIEXPORT jbyte JNICALL Java_com_dramascript_ndktest_NdkTools_getByte
        (JNIEnv *, jobject, jbyte);

/*
 * Class:     com_dramascript_ndktest_NdkTools
 * Method:    getChar
 * Signature: (C)C
 */
JNIEXPORT jchar JNICALL Java_com_dramascript_ndktest_NdkTools_getChar
        (JNIEnv *, jobject, jchar);

/*
 * Class:     com_dramascript_ndktest_NdkTools
 * Method:    getShort
 * Signature: (S)S
 */
JNIEXPORT jshort JNICALL Java_com_dramascript_ndktest_NdkTools_getShort
        (JNIEnv *, jobject, jshort);

/*
 * Class:     com_dramascript_ndktest_NdkTools
 * Method:    getInt
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_dramascript_ndktest_NdkTools_getInt
        (JNIEnv *, jobject, jint);

/*
 * Class:     com_dramascript_ndktest_NdkTools
 * Method:    getLong
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_dramascript_ndktest_NdkTools_getLong
        (JNIEnv *, jobject, jlong);

/*
 * Class:     com_dramascript_ndktest_NdkTools
 * Method:    getFloat
 * Signature: (F)F
 */
JNIEXPORT jfloat JNICALL Java_com_dramascript_ndktest_NdkTools_getFloat
        (JNIEnv *, jobject, jfloat);

/*
 * Class:     com_dramascript_ndktest_NdkTools
 * Method:    getDouble
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_com_dramascript_ndktest_NdkTools_getDouble
        (JNIEnv *, jobject, jdouble);

/*
 * Class:     com_dramascript_ndktest_NdkTools
 * Method:    getString
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_dramascript_ndktest_NdkTools_getString
        (JNIEnv *, jobject, jstring);

/*
 * Class:     com_dramascript_ndktest_NdkTools
 * Method:    getByteArray
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_dramascript_ndktest_NdkTools_getByteArray
        (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     com_dramascript_ndktest_NdkTools
 * Method:    getObject
 * Signature: (Lcom/dramascript/ndktest/User;)Lcom/dramascript/ndktest/User;
 */
JNIEXPORT jobject JNICALL Java_com_dramascript_ndktest_NdkTools_getObject
        (JNIEnv *, jobject, jobject);

/*
 * Class:     com_dramascript_ndktest_NdkTools
 * Method:    getObjectArray
 * Signature: ([Lcom/dramascript/ndktest/User;)[Lcom/dramascript/ndktest/User;
 */
JNIEXPORT jobjectArray JNICALL Java_com_dramascript_ndktest_NdkTools_getObjectArray
        (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     com_dramascript_ndktest_NdkTools
 * Method:    getObjectList
 * Signature: ()Ljava/util/ArrayList;
 */
JNIEXPORT jobject JNICALL Java_com_dramascript_ndktest_NdkTools_getObjectList
        (JNIEnv *, jobject);

/*
 * Class:     com_dramascript_ndktest_NdkTools
 * Method:    callSetData
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_dramascript_ndktest_NdkTools_callSetData
        (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
